#+STARTUP: content
#+STARTUP: overview
#+STARTUP: indent
#+TITLE: Lab notes
#+AUTHOR: Rayan Raddatz de Matos
#+PROPERTY: HEADER-ARGS:python+ :python ./venv/bin/python
#+auto_tangle: t


* TODOS

** IN-PROGRESS Try to play with dask and create some analytics based on the Bruno class examples
- State "IN-PROGRESS" from "TODO"       [2026-01-22 Thu 10:23]

[10:22:49; 22.01.2026]: Yesterday I asked Bruno if he has some
examples to me to play around or if I use the one from his slides.


** TODO Read about HDF5
See the integration with dask, how to use in parallel.

See about zarr also.

* Journal

#+BEGIN: clocktable :scope file :maxlevel 5
#+CAPTION: Clock summary at [2026-01-23 Fri 16:33]
| Headline                                     | Time     |      |      |
|----------------------------------------------+----------+------+------|
| *Total time*                                   | *1d 14:20* |      |      |
|----------------------------------------------+----------+------+------|
| Journal                                      | 1d 14:20 |      |      |
| \_  2026-01-13 Getting used to dask and ray  |          | 3:18 |      |
| \_    Ray                                    |          |      | 0:52 |
| \_  2026-01-14 Side quests                   |          | 4:48 |      |
| \_  2026-01-15 First steps into doreisa      |          | 4:29 |      |
| \_  2026-01-19 Getting Started in Grid5000   |          | 5:00 |      |
| \_  2026-01-20 Continuing with Grid5000      |          | 6:03 |      |
| \_  2026-01-21 Starting with HDF5 and Dask   |          | 3:48 |      |
| \_  2026-01-22 Continuing with HDF5 and Dask |          | 5:33 |      |
| \_  2026-01-23                               |          | 5:21 |      |
#+END:

** 2026-01-13 Getting used to dask and ray
:LOGBOOK:
CLOCK: [2026-01-13 Tue 09:26]--[2026-01-13 Tue 11:52] =>  2:26
:END:
*** Bruno Slides
I will read the slides from Bruno and at the same time will trying
some examples.

Examples from Bruno slides, Fibonacci in Ray:

#+begin_src python :tangle examples/rayfib.py :session *P* :results output :exports both
import ray

@ray.remote
def fib(n):
    if n < 2:
        return n
    x = fib.remote(n-1)
    y = fib.remote(n-2)
    return ray.get(x) + ray.get(y)

print(ray.get(fib.remote(0)))
#+end_src

#+RESULTS:
: 2026-01-13 09:44:27,077	INFO worker.py:2007 -- Started a local Ray instance.
: /home/rayan/graduation/fr/venv/lib/python3.11/site-packages/ray/_private/worker.py:2046: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
:   warnings.warn(
: 0

*** Dask Array

https://docs.dask.org/en/stable/array.html
https://examples.dask.org/array.html

"Community contributions are encouraged"

"Dask will often have as many chunks in memory as twice the number of
active threads."

#+begin_src python :tangle examples/daskarray1.py :session *P* :results output :exports both
import dask.array as da
x = da.random.random((10000, 10000), chunks=(1000, 1000))
print(x)

y = x + x.T
z = y[::2, 5000:].mean(axis=1)
print(z)

print(z.compute())
#+end_src

*** Ray
:LOGBOOK:
CLOCK: [2026-01-13 Tue 14:19]--[2026-01-13 Tue 14:55] =>  0:36
CLOCK: [2026-01-13 Tue 13:31]--[2026-01-13 Tue 13:47] =>  0:16
:END:

Example 1: Square from numbers using ray
#+begin_src python :tangle examples/rayexample1.py :session *P* :results output :exports both
import ray

# Unless you explicitly call ray.init(), the first use of a Ray remote API call will implicitly call ray.init() with no arguments.
ray.init()

# Define the square task.
@ray.remote
def square(x):
    return x * x

# Launch four parallel square tasks.
futures = [square.remote(i) for i in range(4)]

# Retrieve results.
print(ray.get(futures))
# -> [0, 1, 4, 9]
#+end_src

*Actor example:*
#+begin_src python :tangle examples/rayactors.py :session *P* :results output :exports both
# Define the Counter actor.
import ray

@ray.remote
class Counter:
    def __init__(self):
        self.i = 0

    def get(self):
        return self.i

    def incr(self, value):
        self.i += value

# Create a Counter actor.
c = Counter.remote()

# Submit calls to the actor. These calls run asynchronously but in
# submission order on the remote actor process.
for _ in range(10):
    c.incr.remote(1)

# Retrieve final actor state.
print(ray.get(c.get.remote()))
# -> 10
#+end_src

** 2026-01-14 Side quests
:LOGBOOK:
CLOCK: [2026-01-14 Wed 12:11]--[2026-01-14 Wed 14:30] =>  2:19
CLOCK: [2026-01-14 Wed 09:13]--[2026-01-14 Wed 11:11] =>  1:58
CLOCK: [2026-01-14 Wed 08:00]--[2026-01-14 Wed 08:31] =>  0:31
:END:

Get in the lab and leave my computer to the tech guys. After I head
back home to get my on.

[09:58:36; 14.01.2026]: I am now waiting Andres to ask about something
I can do with dask and ray.

[14:53:51; 14.01.2026]: He didn't came today, so I worked with pajeng.

** 2026-01-15 First steps into doreisa
:LOGBOOK:
CLOCK: [2026-01-15 Thu 12:30]--[2026-01-15 Thu 15:35] =>  3:05
CLOCK: [2026-01-15 Thu 09:49]--[2026-01-15 Thu 11:13] =>  1:24
:END:

[12:47:43; 15.01.2026]: I asked Hugo about more info and he tell me
about a [[https://github.com/deisa-project/workflow-example][Workflow Example]] that i could take a look.

[15:31:09; 15.01.2026]: I managed to make it almost work, but there
are some errors in the example, I will focus in make it work tomorrow.

Problem at line 395.

** 2026-01-19 Getting Started in Grid5000
:LOGBOOK:
CLOCK: [2026-01-19 Mon 12:52]--[2026-01-19 Mon 15:32] =>  2:40
CLOCK: [2026-01-19 Mon 09:20]--[2026-01-19 Mon 11:40] =>  2:20
:END:

Next steps are:

[ ] Get comfortable with grid5000.
   - Read starting tutorial
   - Make some examples in experiments in multinode configuration
[ ] Get used with Parallel HDF5.
[ ] Make an example of deisa with parallel writing.


*** Grid5000
Access your data from your laptop using SSHFS:
https://www.grid5000.fr/w/SSH#Mounting_remote_filesystem_.28sshfs.29

SSH Talk:
https://github.com/lnussbaum/slides-lectures/blob/master/ssh/ssh.pdf

SSH via emacs with =C-x C-f /ssh:{login@host,config_alias}/path/to/file=

[15:14:23; 19.01.2026]: I will take some time to fully get familiar
with it since it is different from what I have used before (slurm)

[09:31:56; 20.01.2026]: I will follow some simple tutorials of how to
use it today in the morning.

[09:51:54; 20.01.2026]: Grid5000 experiments can be fully scripted
from the scheduling by using an API

** 2026-01-20 Continuing with Grid5000
:LOGBOOK:
CLOCK: [2026-01-20 Tue 12:55]--[2026-01-20 Tue 16:45] =>  3:50
CLOCK: [2026-01-20 Tue 09:26]--[2026-01-20 Tue 11:39] =>  2:13
:END:

** 2026-01-21 Starting with HDF5 and Dask
:LOGBOOK:
CLOCK: [2026-01-21 Wed 14:32]--[2026-01-21 Wed 16:40] =>  2:08
CLOCK: [2026-01-21 Wed 09:30]--[2026-01-21 Wed 11:10] =>  1:40
:END:

[10:13:06; 21.01.2026]: Today I will focus on understanding HDF5 and
its parallel version.

[10:54:53; 21.01.2026]: HDF5 parallel seems to be working, but I am
not sure, I want to create some dask examples to see how things goes.

[10:55:39; 21.01.2026]: I am currently following this tutorial to get
used with hdf5 in python:
https://docs.h5py.org/en/latest/mpi.html#how-does-parallel-hdf5-work

I had to install some libraries to make it work, something that I
intend to use nix to work after.

[14:34:20; 21.01.2026]: I stopped by a hour, look like there is board
games in the Wednesdays.

[14:35:28; 21.01.2026] Instruction on how to install the h5py:
https://stackoverflow.com/questions/77207467/how-to-build-h5py-with-mpi-support-against-parallel-hdf5-on-linux-2023

** 2026-01-22 Continuing with HDF5 and Dask
:LOGBOOK:
CLOCK: [2026-01-22 Thu 12:31]--[2026-01-22 Thu 16:31] =>  4:00
CLOCK: [2026-01-22 Thu 10:17]--[2026-01-22 Thu 11:50] =>  1:33
:END:


[10:18:48; 22.01.2026]: I forgot to turn on the safety alarms and I
get late today.

[11:36:01; 22.01.2026]: I am trying a Dask example, i need to run the
scheduler before, but the computation don't see to be done, maybe I
need to run other thing also?

[11:41:33; 22.01.2026]: Of course it wouldn't run, I needed to start
workers as well.

[12:32:14; 22.01.2026]: Going back to the examples.

[14:52:18; 22.01.2026]: The same problem with the dead of the head
node was happening in the g5k, but using a ray list command fixed it
and I don't know way.

[14:55:36; 22.01.2026]: Moving the
#+begin_src shell :results output :exports both
ray start --address 127.0.0.1:6379                         > .logs/ray-worker.log 2>&1
#+end_src
line to after the
#+begin_src shell :results output :exports both
# Start analytics (uses venv python)
"$PY" -m analytics.avg 2>.logs/analytics.e&
ANALYTICS_PID=$!
#+end_src
also make it works...

Maybe the cluster die by being idle...

[15:42:59; 22.01.2026]: I understand that the problem is that deisa
had some delay to create the simulation_head, so a delay after it
starts (or a lazy computer) is enough to make it works. I just put a
sleep 0.5 there and everything is perfect.

[15:47:12; 22.01.2026]: I will know write the same example of the hdf5
writing with deisa and then after I will run a experiment to see the times.

[16:31:17; 22.01.2026]: See about zarr and also how to use the hdf5.
** 2026-01-23
:LOGBOOK:
CLOCK: [2026-01-23 Fri 12:11]--[2026-01-23 Fri 16:32] =>  4:21
CLOCK: [2026-01-23 Fri 10:11]--[2026-01-23 Fri 11:11] =>  1:00
:END:

[10:12:05; 23.01.2026]: Here we are, I will now try to play with dask
and hdf5 to save an analytics from deisa.

[15:49:01; 23.01.2026]: Looks to me that it isn't possible to just
keeping writing in the same dataset after it was created...

[16:10:42; 23.01.2026]: Looks that deisa didn't support the writing of
HDF5 files... I will try to see with the newer versions to see if
everything changed.
